server:
  port: 8080

spring:
  application:
    name: rate-limiter-service
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      ssl:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
